### PR TITLE
Remove /vendor caching in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
It is toxic 🧪 makes CI unstable

### CODE REVIEW

**Comment by szepeviktor** [comment]
`~/.composer/cache` 👉 `vendor` takes only a single unzip operation

**Comment by mnavarrocarter** [comment]
Yeah, you are not the first one that I've heard that from. I lot of people I respect say that could create really bad side effects. I myself still need to find an issue with it though. 

I will merge it since it does no harm.

**Comment by szepeviktor** [comment]
> no harm.

It does negative harm!


You're welcome.

**Comment by mnavarrocarter** [comment]
Sorry @szepeviktor. Not very polite on my part. Thank you!

**Pull request merged**
